# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node

name: Node.js CI

on:
  push:
    branches: [ main, heroku-deployment, testing ]
  pull_request:
    branches: [ main, heroku-deployment, testing ]

jobs:
  build-windows:

    runs-on: [ windows-latest ]

    strategy:
      max-parallel: 1
      matrix:
        node-version: [14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test


  build-macos:

    needs: build-windows

    runs-on: [ macos-latest ]

    strategy:
      max-parallel: 1
      matrix:
        node-version: [14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test